### ISSUE TITLE
pub get error in the example app

### ISSUE THREAD

**Issue by BradKwon** [jicang/healywatch_reactive#80]
Hi,

I tried to run the example app on my machine from master branch and I got this `pub get` error.
FYI: `very_good packages get -r`I used in the log is same as `flutter pub get` but with recursive options to execute `pub get` in all subdirectories.

Please fix this and make sure the example app up and running.

Log:
````
hyeon-gu.kwon@HealyWo72SYML7M healywatch_reactive % very_good packages get -r
✓ Running "flutter packages get" in /Users/hyeon-gu.kwon/dev/healywatch_reactive/example (2.9s)
ProcessException: Standard out
Running "flutter pub get" in example...
Standard error
Because every version of healy_watch_sdk from path depends on flutter_plugin from git and healywatch_reactive depends on flutter_plugin from path, healy_watch_sdk from path is forbidden.
So, because healywatch_reactive depends on healy_watch_sdk from path, version solving failed.
pub get failed (1; So, because healywatch_reactive depends on healy_watch_sdk from path, version solving failed.)
  Command: flutter packages get
````

**Comment by BradKwon** [comment]
With the updated Sdk I got via email, this `pub get` error is fixed. However, when I run the example app on my iOS device, another runtime error arisen.

Please check this and fix please.

![Screenshot 2022-06-24 at 12 01 50](https://user-images.githubusercontent.com/5119467/175516865-88edc083-99a7-4e54-8d2a-65108d6027c1.png)

**Comment by badjio** [comment]
The error is back again in latest version, please revert back this change to fix it
![Screenshot 2022-07-21 at 09 58 11](https://user-images.githubusercontent.com/15873766/181519696-393fadf6-99a0-4a4b-81ff-b153d442cc91.png)

**Comment by YongHealyWorld** [comment]
From @badjio : 
''#80 the fix is simple if it’s okay to push it ourselves to the main repository, I’ll do that, though Hyeon Gu Kwon (DE) reported another error in same issue page, that I didn’t face yet, so it should be also fixed.''

Yong comment:
This could be likely closed in a week.

**Comment by badjio** [comment]
The main error reported above is fixed now.

**Comment by BradKwon** [comment]
The above runtime error is fixed.
